const me=S(),u=()=>DB.users.find(x=>x.username==me?.username);
if(!u()||!u().idOk||!u().faceOk||!u().policy)location.replace(me&&u()?'id-verification.html':'login.html');
const mine=()=>DB.requests.filter(r=>r.user==me.username),ck=(l,b)=>`<li class="${b?'y':'n'}">${b?'✓':'○'} ${l} — ${b?'Done':'Action Required'}</li>`;
function reqForm(id){const c=con(id);modal(`<h3>Request Ticket</h3><p class="muted">${c.name} · ${c.date}</p><label>Category</label><select id="rc">${c.cats.map(k=>`<option>${k.n} — ${P(k.p)} (${rem(k)} left)</option>`).join('')}</select><label>Quantity (max 4)</label><input id="rq" type="number" min="1" max="4" value="1"><br><button class="btn" data-a="submit" data-id="${id}">Submit Request</button>`)}
const rows=f=>mine().filter(f||(()=>1));
shell({role:'user',menu:[['Dashboard','🏠'],['Browse Concerts','🎤'],['My Requests','📝'],['My Tickets','🎫'],['Transaction History','💳'],['Messages','✉️'],['Notifications','🔔'],['Verification','✅'],['Profile','👤'],['Privacy & Policies','📜']],
init(){if(sessionStorage.intent){reqForm(sessionStorage.intent);sessionStorage.removeItem('intent')}},
panel(p){const M=mine(),n=s=>M.filter(r=>s.includes(r.status)).length;
if(p=='Dashboard')return`<h3 style="margin-bottom:14px">Welcome back, ${me.name}!</h3>`+grid([['Active Requests',n(['Pending','Under Review','Verified','Approved'])],['Pending Requests',n(['Pending'])],['Approved Tickets',n(['Approved'])],['Released Tickets',n(['Released'])],['Notifications',DB.notes.length]])+'<h2>Account Verification</h2>'+panel2('Verification');
if(p=='Browse Concerts')return`<div class="grid">${DB.concerts.filter(c=>c.pub).map(c=>ccard(c).replace('Get Ticket','Request Ticket')).join('')}</div>`;
if(p=='My Requests')return`<div class="card">${tbl(['Request ID','Concert','Category','Qty','Date','Status','Action'],M.map(r=>[r.id,con(r.cid).name,r.cat,r.qty,r.date,tag(r.status),`<button class="btn sm" data-a="vd" data-id="${r.id}">View Details</button>${r.status=='Pending'?`<button class="btn sm bad" data-a="cx" data-id="${r.id}">Cancel</button>`:''}`]))}</div>`;
if(p=='My Tickets'){const t=M.filter(r=>r.status=='Released');return`<div class="grid">${t.map(r=>{const c=con(r.cid);return`<div class="card"><div class="cimg" style="background:linear-gradient(135deg,${c.g})">${c.artist}</div><h3>${c.name}</h3><p class="muted">${c.venue}<br>${c.date} · ${c.time}<br>${r.cat} · Ticket #KT-${r.id.slice(2)}-${r.qty}</p><div style="margin:10px 0;width:70px;height:70px;border:2px dashed #999;display:flex;align-items:center;justify-content:center;font-size:.6rem">QR</div><button class="btn sm" data-a="vt" data-id="${r.id}">View Ticket</button><button class="btn sm out" style="color:var(--pri)" data-a="qr" data-id="${r.id}">Show QR</button></div>`}).join('')||'<p class="muted">No released tickets yet.</p>'}</div>`}
if(p=='Transaction History')return`<div class="card">${tbl(['Request','Concert','Amount','Status'],M.map(r=>[r.id,con(r.cid).name,P(price(r)),tag(r.status)]))}</div>`;
if(p=='Messages'||p=='Notifications')return`<div class="card">${DB.notes.map(n=>`<p style="padding:8px 0;border-bottom:1px solid #eee">${n}</p>`).join('')}</div>`;
if(p=='Verification')return panel2(p);
if(p=='Profile')return`<div class="card"><p><b>${u().name}</b></p><p class="muted">@${u().username} · ${u().email}<br>Registered ${u().date}</p></div>`;
return`<div class="card"><p>You accepted the Privacy Policy, User Agreement and Safety &amp; Transaction Policy.</p></div>`},
act(a,id){const r=DB.requests.find(x=>x.id==id);
if(a=='submit'){const c=con(id),q=+$('#rq').value;if(!(q>=1&&q<=4))return toast('Quantity must be 1-4.');const k=c.cats[$('#rc').selectedIndex];if(rem(k)<q)return toast('Not enough stock.');const rid='R-'+(1001+DB.requests.length);DB.requests.unshift({id:rid,user:me.username,name:me.name,cid:c.id,cat:k.n,qty:q,status:'Pending',date:now().slice(0,10)});DB.notes.unshift(`Request ${rid} submitted.`);log('User','Submitted Request','Ticket Request',rid);closeM();toast('Request submitted!');goto('My Requests')}
if(a=='cx'){r.status='Cancelled';log('User','Cancelled Request','Ticket Request',id)}
if(a=='vd')modal(`<h3>${r.id}</h3><p>${con(r.cid).name}<br>${r.cat} × ${r.qty} — ${P(price(r))}<br>${tag(r.status)}</p><p class="muted">Track: Pending → Under Review → Verified → Approved → Released</p>`);
if(a=='vt'||a=='qr')modal(`<h3>${a=='qr'?'Ticket QR':'Ticket'} KT-${id.slice(2)}</h3><div style="width:160px;height:160px;margin:12px auto;background:repeating-conic-gradient(#000 0 25%,#fff 0 50%) 0 0/24px 24px"></div><p class="muted" style="text-align:center">QR placeholder</p>`)}});
function panel2(){return`<div class="card"><ul class="chk">${ck('Account Registered',1)}${ck('Valid ID Verified',u().idOk)}${ck('Facial Verification Completed',u().faceOk)}${ck('Privacy Policy Accepted',u().policy)}${ck('User Agreement Accepted',u().policy)}</ul></div>`}
